<?php
/**
 * Custom Settings for Listing single post
 *
 * @package Finder/ACF/Settings/Listing single post
 */

acf_add_local_field_group(
	array(
		'key'                   => 'group_616536889db27',
		'title'                 => 'Finder Archive Listing Attribute	Options',
		'fields'                => array(
			array(
				'key'               => 'field_616536889fa04',
				'label'             => 'Archive Style',
				'name'              => 'archive_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'real-estate' => 'Real Estate',
					'city-guide'  => 'City Guide',
					'car-finder'  => 'Car Finder',
				),
				'default_value'     => 'real-estate',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_616536889fa0d',
				'label'             => 'Real Estate Archive View Style',
				'name'              => 'real_estate_archive_view_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_616536889fa04',
							'operator' => '==',
							'value'    => 'real-estate',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'default' => 'Default',
					'price'   => 'Price',
					'address' => 'Address',
					'badge'   => 'Badge',
				),
				'default_value'     => 'default',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key' => 'field_616eb4c3bd77b',
				'label' => 'Car Finder Archive View Style',
				'name' => 'car_finder_archive_view_style',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_616536889fa04',
							'operator' => '==',
							'value' => 'car-finder',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'price' => 'Price',
					'location' => 'Location',
					'boxed' => 'Boxed',
					'badge' => 'Badge',
					'year'  => 'Year',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key'               => 'field_616ea5a414650',
				'label'             => 'Archive Listing Icon Classes',
				'name'              => 'archive_listing_icon_classes',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'hp_listing_attribute',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	)
);

acf_add_local_field_group(array(
	'key' => 'group_62e3d58a946fb',
	'title' => 'Archive attribute filter Styles',
	'fields' => array(
		array(
			'key' => 'field_62e3d5c115449',
			'label' => 'Set Radio Filter Style',
			'name' => 'set_radio_filter_style',
			'type' => 'select',
			'instructions' => 'Modifies archive page radio button filter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style1' => 'Style 1',
				'style2' => 'Style 2',
			),
			'default_value' => 'style1',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_62e761dcd99cd',
			'label' => 'Set Number Range Style',
			'name' => 'set_number_range_style',
			'type' => 'select',
			'instructions' => 'Modifies archive page number range filter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style1' => 'Style 1',
				'style2' => 'Style 2',
			),
			'default_value' => 'style1',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_631031491b937',
			'label' => 'Enter Number Range prefix',
			'name' => 'number_range_prefix',
			'type' => 'text',
			'instructions' => 'Enter prefix like currency symbols and units',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'hp_listing_attribute',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(
	array(
		'key'                   => 'group_615ea06da8010',
		'title'                 => 'Finder Single Listing Attribute Options',
		'fields'                => array(
			array(
				'key'               => 'field_615ea0dfbfd3b',
				'label'             => 'Single Style',
				'name'              => 'single_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'real-estate' => 'Real Estate',
					'city-guide'  => 'City Guide',
					'car-finder'  => 'Car Finder',
				),
				'default_value'     => 'real-estate',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_615ea3483ecb9',
				'label'             => 'Real Estate View Style',
				'name'              => 'real_estate_view_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_615ea0dfbfd3b',
							'operator' => '==',
							'value'    => 'real-estate',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'location' => 'Location',
					'icon'     => 'Icon',
					'badge'    => 'Badge',
					'price'    => 'Price',
				),
				'default_value'     => 'location',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_616d81d384a7d',
				'label'             => 'City Guide View Style',
				'name'              => 'city_guide_view_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_615ea0dfbfd3b',
							'operator' => '==',
							'value'    => 'city-guide',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'primary'  => 'Primary',
					'secondary'  => 'Secondary',
					'price'    => 'Price',
				),
				'default_value'     => 'default',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_6167cd07e5b91',
				'label'             => 'Car Finder View Style',
				'name'              => 'car_finder_view_style',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_615ea0dfbfd3b',
							'operator' => '==',
							'value'    => 'car-finder',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'badge'  => 'Badge',
					'price'  => 'Price',
					'inline' => 'Inline',
				),
				'default_value'     => 'price',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_616ea4afb11a0',
				'label'             => 'Single Listing Icon Classes',
				'name'              => 'single_listing_icon_classes',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'hp_listing_attribute',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	)
);

