<?php
/**
 * Custom Settings for Page Options.
 *
 * @package Finder/ACF/Settings/Page
 */

acf_add_local_field_group(
	array(
		'key'                   => 'group_6179020ec9224',
		'title'                 => 'Header Settings',
		'fields'                => array(
			array(
				'key'               => 'field_617940421bce3',
				'label'             => 'Enable Custom Header ?',
				'name'              => 'is_custom_header',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_61791a0728402',
				'label'             => 'Enable Sticky Header ?',
				'name'              => 'is_sticky_header',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_617a3833aa8fa',
				'label'             => 'Enable Navbar Dark ?',
				'name'              => 'is_header_navbar_dark',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_618b6b9e04217',
				'label'             => 'Enable Transparent Navbar ?',
				'name'              => 'is_header_navbar_transparent',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_617a387baa8fb',
				'label'             => 'Enable Signin Button ?',
				'name'              => 'header_enable_signin_button',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'yes',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_61796ae081871',
				'label'             => 'Enable Buy Finder Button ?',
				'name'              => 'header_enable_buy_finder_button',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_61796da3c457b',
				'label'             => 'Buy Finder Button Color',
				'name'              => 'buy_finder_button_color',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'primary' => 'Primary',
					'accent'  => 'Accent',
					'success' => 'Success',
					'danger'  => 'Danger',
					'warning' => 'Warning',
					'info'    => 'Info',
					'dark'    => 'Dark',
					'link'    => 'Link',
				),
				'default_value'     => 'primary',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_61797092bb20c',
				'label'             => 'Buy Finder Button Text',
				'name'              => 'buy_finder_button_text',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Buy Finder',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_6179711dd3054',
				'label'             => 'Buy Finder Button Size',
				'name'              => 'buy_finder_button_size',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'xs' => 'Extra Small',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value'     => 'sm',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617971f8a98ca',
				'label'             => 'Buy Finder Button Url',
				'name'              => 'buy_finder_button_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '#',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_6179722ba98cb',
				'label'             => 'Buy Finder Button Icon',
				'name'              => 'buy_finder_button_icon',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'fi-cart',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_617972787e18e',
				'label'             => 'Buy Finder Button Shape',
				'name'              => 'buy_finder_button_shape',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61796ae081871',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'default'      => 'Default',
					'rounded-pill' => 'Pill',
					'rounded-0'    => 'Square',
				),
				'default_value'     => 'rounded-pill',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_61797483910ba',
				'label'             => 'Enable Add Listing Button ?',
				'name'              => 'header_enable_add_listing_button',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'yes',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_617974efbeb38',
				'label'             => 'Add Listing Button Color',
				'name'              => 'add_listing_button_color',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61797483910ba',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'primary' => 'Primary',
					'accent'  => 'Accent',
					'success' => 'Success',
					'danger'  => 'Danger',
					'warning' => 'Warning',
					'info'    => 'Info',
					'dark'    => 'Dark',
					'link'    => 'Link',
				),
				'default_value'     => 'primary',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_61797533ba14c',
				'label'             => 'Add Listing Button Text',
				'name'              => 'add_listing_button_text',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61797483910ba',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Add Property',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_6179759be65ea',
				'label'             => 'Add Listing Button Size',
				'name'              => 'add_listing_button_size',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61797483910ba',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'xs' => 'Extra Small',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value'     => 'sm',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617975d6fe094',
				'label'             => 'Add Listing Button Icon',
				'name'              => 'add_listing_button_icon',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61797483910ba',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'fi-plus',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_6179760a7a791',
				'label'             => 'Add Listing Button Shape',
				'name'              => 'add_listing_button_shape',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61797483910ba',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'default'      => 'Default',
					'rounded-pill' => 'Pill',
					'rounded-0'    => 'Square',
				),
				'default_value'     => 'rounded-0',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a3053ea7b0',
				'label'             => 'Enable Post Resume Button ?',
				'name'              => 'header_enable_post_resume_button',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_617a323b80207',
				'label'             => 'Post Resume Button Color',
				'name'              => 'post_resume_button_color',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'primary' => 'Primary',
					'accent'  => 'Accent',
					'success' => 'Success',
					'danger'  => 'Danger',
					'warning' => 'Warning',
					'info'    => 'Info',
					'dark'    => 'Dark',
					'link'    => 'Link',
				),
				'default_value'     => 'primary',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a327d80208',
				'label'             => 'Post Resume Button Text',
				'name'              => 'post_resume_button_text',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Post resume',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_617a32c880209',
				'label'             => 'Post Resume Button Size',
				'name'              => 'post_resume_button_size',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'xs' => 'Extra Small',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value'     => 'sm',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a33058020a',
				'label'             => 'Post Resume Button Icon',
				'name'              => 'post_resume_button_icon',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'fi-plus',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_617a333d8020b',
				'label'             => 'Post Resume Button Shape',
				'name'              => 'post_resume_button_shape',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'default'      => 'Default',
					'rounded-pill' => 'Pill',
					'rounded-0'    => 'Square',
				),
				'default_value'     => 'rounded-pill',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a33a92dc37',
				'label'             => 'Post Resume Button Url',
				'name'              => 'post_resume_button_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3053ea7b0',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '#',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a3588a292d',
				'label'             => 'Enable Employers Button ?',
				'name'              => 'header_enable_employers_button',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617940421bce3',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_617a35eb24647',
				'label'             => 'Employers Button Color',
				'name'              => 'employers_button_color',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3588a292d',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'primary' => 'Primary',
					'accent'  => 'Accent',
					'success' => 'Success',
					'danger'  => 'Danger',
					'warning' => 'Warning',
					'info'    => 'Info',
					'dark'    => 'Dark',
					'link'    => 'Link',
				),
				'default_value'     => 'link',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a363224648',
				'label'             => 'Employers Button Text',
				'name'              => 'employers_button_text',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3588a292d',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'For employers',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_617a36a924649',
				'label'             => 'Employers Button Url',
				'name'              => 'employers_button_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3588a292d',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '#',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_617a36f22464a',
				'label'             => 'Employers Button Size',
				'name'              => 'employers_button_size',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_617a3588a292d',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'xs' => 'Extra Small',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value'     => 'sm',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'return_format'     => 'value',
				'placeholder'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	)
);

acf_add_local_field_group(
	array(
		'key'                   => 'group_618b752f5481b',
		'title'                 => 'Page Settings',
		'fields'                => array(
			array(
				'key'               => 'field_618b75f3eb3d8',
				'label'             => 'Disable Page Header ?',
				'name'              => 'disable_page_header',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => '',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_618b76351a752',
				'label'             => 'Body Css Class',
				'name'              => 'body_css_class',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	)
);

acf_add_local_field_group(
	array(
		'key'                   => 'group_618113b79dcff',
		'title'                 => 'Footer Settings',
		'fields'                => array(
			array(
				'key'               => 'field_618113f5ed163',
				'label'             => 'Enable Custom Footer',
				'name'              => 'enable_custom_footer',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
				),
				'allow_null'        => 1,
				'other_choice'      => 0,
				'default_value'     => '',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_61811ca75de53',
				'label'             => 'Footer version',
				'name'              => 'footer_version',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'default' => 'Default',
					'v1'      => 'v1',
					'v2'      => 'v2',
					'v3'      => 'v3',
					'v4'      => 'v4',
					'v5'      => 'v5',
					'v6'      => 'v6',
				),
				'default_value'     => 'default',
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 0,
				'return_format'     => 'value',
				'ajax'              => 0,
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_618153c3dc971',
				'label'             => 'Footer Copyrights',
				'name'              => 'footer_copyrights',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '!=',
							'value'    => 'default',
						),
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '<span class=\\"text-link\\">© All rights reserved. Made by </span><a class=\\"nav-link-light fw-bold \\" href=\\"https://madrasthemes.com\\" target=\\"_blank\\" rel=\\"noopener\\"> Finder</a>',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_6182276e2768f',
				'label'             => 'Footer Banner Title',
				'name'              => 'footer_banner_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Download Our App',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_61822c56f3219',
				'label'             => 'Footer Banner Description',
				'name'              => 'footer_banner_description',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Find everything you need for buying, selling & renting property in our new Finder App!',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_61822f94a38ff',
				'label'             => 'Footer Banner Image',
				'name'              => 'footer_banner_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_618236c08992e',
				'label'             => 'Footer Banner App Store Image',
				'name'              => 'footer_banner_app_store_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_618a5cbb7940a',
				'label'             => 'Footer Banner App Store Image Url',
				'name'              => 'footer_banner_app_store_image_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_61823b35d2e1b',
				'label'             => 'Footer Banner Google	Play Image',
				'name'              => 'footer_banner_google_play_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_618a5d027940e',
				'label'             => 'Footer Banner Google Play Image Url',
				'name'              => 'footer_banner_google_play_image_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v2',
						),
					),
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v4',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_61823ed17c2c4',
				'label'             => 'Footer Form Title',
				'name'              => 'footer_form_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Subscribe to our newsletter',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_618243eab7e0a',
				'label'             => 'Footer Form',
				'name'              => 'footer_form',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '<form class="subscription-form validate"><div class="form-group form-group-light rounded-pill"><div class="input-group flex-nowrap"><span class="input-group-text text-muted"><i class="fi-mail"></i></span><input class="form-control" type="email" name="EMAIL" placeholder="Your email" required></div><button class="btn btn-primary rounded-pill" type="submit" name="subscribe">Subscribe*</button></div></form>',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
			),
			array(
				'key'               => 'field_61824176f52cb',
				'label'             => 'Footer Form Description',
				'name'              => 'footer_form_description',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_618113f5ed163',
							'operator' => '==',
							'value'    => 'yes',
						),
						array(
							'field'    => 'field_61811ca75de53',
							'operator' => '==',
							'value'    => 'v1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '*Subscribe to our newsletter to receive early discount offers, updates and new products info.',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	)
);
